# Generated by Django 5.2.1 on 2025-05-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_xdfle7', upload_to='images/'),
        ),
    ]
